auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: dongyingzi.gtihub.io
url: http://dongyingzi.github.io
feed: /atom.xml
author_info: <a href="http://dongyingzi.github.io/">dongyingzi</a>
